version: '2.1'
services:
  library_backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      MYSQL_DATABASE: library_database
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: library_database
