version: '3'
services:
  library_backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
      MYSQL_DATABASE: library_database
    depends_on:
      - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: library_database
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
